export const enum Module {
  Heatmap = 'HeatmapUtil',
  ValuationColoring = 'ValuationColoringUtil',
  LandSocket = 'LandSocketUtil',
  ArcanaProvider = 'ArcanaProviderUtil',
  PortfolioSlice = 'PortfolioSliceFetch',
  WagmiConfig = 'WagmiConfig',
  ITRMService = 'ITRMService',
  AuthService = 'AuthService',
  TextureUtil = 'TextureUtil',
  ArcanaAuth = 'ArcanaAuthUtil',
  CoinGecko = "CoinGeckoUtil",
  ITRMValAnalytics = "ValAnalyticsUtil",
  ITRMLandValuation = "LandValuationUtil",
  ITRMAuth = "AuthUtil",
  LoginComponent = "LoginComponent",
}