"use client"

import './global.css';
import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import { Plus_Jakarta_Sans } from 'next/font/google';
import HeaderComponent from '../component/header/header.component';
import store from '../state/store';
import { Provider } from 'react-redux';
import RootProvider from '../providers/providers';
import NavbarUI from '../ui/navbar/navbar.ui';
import FontIcons from 'next/font/local';
import SubHeader from '../ui/subHeader/subHeader.ui';
import { fetchCurrencyData } from '../utils/api';
import { setCurrencyValues } from '../state/currencySlice';
import FooterUI from '../ui/common/footer.ui';
import MobileUI from '../ui/mobile/mobile.ui';

const plusJakarta = Plus_Jakarta_Sans({ subsets: ['latin'], display: 'block', variable: '--jakarta-font' });
const fontIcons = FontIcons({ src: '../../public/fonts/fonts-icons/iconSet01.ttf', display: 'block', variable: '--icons-font' });

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

const list = [
  {
    url: "/metaverseexplorer",
    label: "Metaverse explorer",
    icon: "b",
    isExternal: false,
  },
  {
    url: "/stake",
    label: "Stake MGH",
    icon: "d",
    isExternal: false,
  },
  {
    url: "https://snapshot.org/#/metagamehub.eth",
    label: "Governance",
    icon: "a",
    isExternal: true,
  },
];

const subHeaderList = [
  {
    name: "Heatmap",
    route: "metaverseexplorer",
  },
  {
    name: "Portfolio",
    route: "metaverseexplorer/portfolio",
  },
  {
    name: "Watchlist",
    route: "metaverseexplorer/watchlist",
  },
  {
    name: "Analytics",
    route: "metaverseexplorer/analytics",
  },
];

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const [isConnected, setIsConnected] = useState<boolean>(false);

  useEffect(() => {
    // Asynchronous function that updates data for Currency coins
    const updateCurrencyData = async () => {
      const currencyData = await fetchCurrencyData();
      if (currencyData) store.dispatch(setCurrencyValues(currencyData));
    };

    void updateCurrencyData();
  }, []);

  return (
    <Provider store={store}>
      <html lang="en" className={`${plusJakarta.variable} ${fontIcons.variable}`}>
        <body className="font-plus text-nm-dm-highlight bg-nm-highlight">
          <div className='hidden xl:block'>
            <RootProvider>
              <div className={`w-full h-screen grid grid-cols-[137px_1fr] ${isConnected ? 'grid-rows-[226px_1fr]' : 'grid-rows-[70px_1fr]'} `}>
                <nav className="bg-nm-gray row-span-2">
                  <NavbarUI list={list} route={pathname} />
                </nav>
                <HeaderComponent setIsConnected={(isConnectedChild: boolean) => setIsConnected(isConnectedChild)} />
                <main className='px-16'>
                  {pathname !== '/stake' && <SubHeader optionList={subHeaderList} />}
                  {children}
                  {isConnected && pathname !== '/metaverseexplorer/analytics' && <FooterUI />}
                </main>
              </div>
            </RootProvider>
          </div>
          <div className="xl:hidden h-screen w-screen bg-white fixed inset-0 z-[99]">
            <MobileUI />
          </div>
        </body>
      </html>
    </Provider >
  )
}