// For nftValuation


//First Filter
export type Status =

| 'buy_now'
| 'on_auction'

type Currency =

| 'eth'
| 'usd'
| 'sol'

//Second Filter
export type Price = {
  minPrice: number
  maxPrice: number
  currency: Currency
}

//Third Filter
export type Quantity =

| 'all_items'
| 'single_items'
| 'bundles'

//Fourth Filter
export type Currencies =
| 'eth'
| 'weth'
| 'dai'
| 'usdc'

//Last Filter
export type TraitFilter =

  | 'background'
  | 'dance'
  | 'music'
  | 'expression'
  | 'ears'
  | 'nose'
  | 'mouth'
  | 'head'
  | 'neck'
  | 'top'
  | 'eyewear'
  | 'eyes'
  | 'fur'
  | 'sex'

export type Background =

  | 'Mansion'
  | 'Heaven'
  | 'Lambo'
  | 'Beach'
  | 'Backalley'
  | 'Tiki'
  | 'Gallery'
  | 'Dunes'
  | 'Spaceship'
  | 'Swamp'
  | 'Garden'
  | 'Markets'
  | 'Pass'
  | 'FTW (F*ck The War)'
  | 'Mystic Valley'
  | 'Thank You For Having Us'
  | 'The Front'
  | 'Dancing in the Shroomlight'
  | 'FLUF Haus Miami 2021'
  | 'Star Explorer'
  | 'ASTO Discovery Portal'
  | 'After Party'
  | 'Fluf Haus LA 2022'
  | 'The Wall'
  | 'Pre-Game'
  | 'Forest'
  | 'Studio'
  | 'Art Gallery'
  | 'Desert'
  | 'Space Hangar'
  | 'Apocalypse'
  | 'Igloo'
  | 'Playa'
  | 'Party House'
  | 'Pj Runway'
  | 'Zen Den'
  | 'High School'
  | 'Club'
  | 'Temple'

export type Dance =
  | 'Groove'
  | 'Bob'
  | 'Side To Side'
  | 'Subtle Nod'
  | 'Round'
  | 'Big Nod'
  | 'Side Nod'
  | 'Turn'

export type Ears =

| 'Steel Rings'
| 'Steel Studs'
| 'Steel Rings & Studs'
| 'Gold Rings'
| 'FLUF Tag'
| 'Gold Bows'
| 'Gold Rings & Studs'
| 'Red Ribbon'
| 'Bandaged'
| 'Diamond Studs'
| 'Bit Ear'
| 'Diamond Cross Earring'
| 'Santa Hat'

export type Expression =

| 'Mouth Open (Right)'
| 'Blank'
| 'Anger'
| 'Mouth Open (Middle)'
| 'Mouth Open (Right) + Wink'
| 'Mouth Open (Left)'
| 'Smile'
| 'Smile + Wink'
| 'Sad'
| 'Grin'
| 'Blank + Wink'
| 'Mouth Open (Middle) + Wink'
| 'Mouth Open (Left) + Wink'
| 'Wonder'
| 'Grin + Wink'

export type Eyes =

| 'Green'
| 'Brown'
| 'Blue'
| 'Yellow'
| 'Green (Dilated)'
| 'Cat (Blue)'
| 'Cat (Brown)'
| 'Purple'
| 'Red'
| 'Fire'
| 'Heart (Blue)'
| 'Red (Dilated)'
| 'Thirties'
| 'Heart (Red)'
| 'Scribble'
| 'Dollars'
| 'Xs'
| 'Reptile (Yellow)'
| 'Reptile (White)'
| 'Reptile (Cream)'
| 'Glowing Red'
| 'Demon'
| 'Blast'
| 'Glowing White'
| 'Portal'
| 'Dead'
| 'Hypnotic'
| 'Mandala'
| 'Purple Rings'
| 'Inverted'
| 'Inverted (Purple)'
| 'Zombie'
| 'Zombie (Inverted)'
| 'Gold'
| 'Silver'

export type Eyewear =

| 'Sunglasses'
| 'Shutter Glasses'
| 'Aviator'
| 'Star Glasses'
| 'Designer Glasses'
| 'Round Glasses'
| 'Bug Eye Glasses'
| 'Neon Glasses'
| 'Heart Glasses'
| 'Fake Eyelashes'
| 'Speed Glasses'
| 'Dive Goggles'
| 'Eye Patch'
| 'Safety Glasses'
| 'Cyberpunk Glasses'
| 'Deal With It Glasses'
| '3D Glasses'
| 'Steampunk Goggles'

export type Fur =

| 'Grey'
| 'Winter'
| 'Brown'
| 'Black & White'
| 'Sandy'
| 'Darkness'
| 'Peppermint'
| 'Orange'
| 'Red'
| 'Sky'
| 'Camo'
| 'Zebra'
| 'Tiger'
| 'Cow'
| 'Cheetah'
| 'Moody Blue'
| 'Marshmellow'
| 'Ice Cream'
| 'Raspberry Ripple'
| 'Smoothie'
| 'Honeycomb'
| 'Candy Floss'
| 'Parrot'
| 'Bully'
| 'Tie Dye'
| 'Highlighter'
| 'Hawk'
| 'Retro'
| 'Guernica'
| 'Blue Blood'
| 'Pheonix'
| 'Zombie (Black)'
| 'Zombie (Grey)'
| 'Zombie (Green)'
| 'Zombie (Red)'
| 'Barney'
| 'Grinch'
| 'Kandinsky'
| 'Hirst'
| 'Kanagawa'
| 'Blossom'
| 'Starry Night'
| 'Avatar'
| 'Holographic'
| 'Silver'
| 'Gold'

export type Head =

| 'Beanie'
| 'Flower Crown'
| 'Bandana'
| 'Birthday Hat'
| 'Conical Hat'
| 'Cowboy Hat'
| 'Pirate Hat'
| 'Tuft (Base)'
| 'Mohawk (Base)'
| 'Afro (Base)'
| 'Army Helmet'
| 'FLUF Cap'
| 'Mullet (Base)'
| 'Sombrero'
| 'Propeller Hat'
| 'Tennis Hat'
| 'Sun Visor'
| 'Tuft (Black)'
| 'Tuft (Blonde)'
| 'Devil Horns'
| 'Mohawak (Red)'
| 'Mullet (Black)'
| 'Mohawak (Black)'
| 'Afro (Ginger)'
| 'Halo'
| 'Mullet (Orange)'
| 'Afro (Black)'
| 'Glod Cap'
| 'Beer Hat'
| 'Holographic Cap'
| 'Crown'

export type Mouth =

| 'Lollipop'
| 'Joint'
| 'Cigarette'
| 'Carrot'
| 'Pipe'
| 'Party Horn'
| 'Whistle'
| 'Lip Piercings'
| 'Cigar'
| 'Pacifier'
| 'Lipstick'
| 'Medical Mask'
| 'Tongue Out'
| 'Mooncrust Pizza'
| 'Demon Mask'

export type Music =

| 'Follow You'
| 'Run Rabbit'
| 'Coffee and Carrots'
| 'Ear Wobbler'
| 'Reggae Rabbits'
| 'Disco Rabbit'
| 'Electric Carrots'
| 'Desert Digging'
| 'Rabbiton'
| 'Space Fluffle'
| 'Floating or Flying'
| 'Hop On By'
| 'Back in the Burrow'
| 'Eating Carrots in the Dark'
| 'Dubhop'
| 'FLUF You Up'
| 'What the FLUF'
| 'I Like to Party'
| 'Beyond the Gates'
| 'Hop With Me'
| 'NFT (Instrumental)'
| 'I Love FLUF'
| 'Messiah'
| 'Let The Story Begin'
| 'FLUF Ocean'
| 'L.O.V.E.'
| 'Stardust'
| 'Lucky Foot'
| 'Higher'
| 'Latin Fiesta'
| 'All I Need'
| 'Shadows'
| "Wouldn't It Be"
| 'Eating Carrots_in_the_Dark'
| 'How Could You'
| 'Let It Go'
| 'I Like_to_Party'
| 'Hop On_By'
| 'Beyond the_Gates'
| 'FLUF You_Up'
| 'What the_FLUF'
| 'Back in_the_Burrow'
| 'How You Feel'
| 'Floting or_Flying'
| 'Hop With_Me'
| 'Daft Bear'
| 'Tulum Bear'
| 'Altered Bear'
| 'Bear Marley'
| 'Bear Friends'
| 'Robobear'
| 'Show Bear Love'
| 'Tropical Bear'
| 'Bear Bass'
| 'Bear Bot'
| 'Bear Beach'
| 'Beartron'
| 'Ibiza Bear'
| 'Rufus Du Bear'
| 'Termabear'
| 'Rasta Bear'

export type Neck =

| 'Bowtie (Red)'
| 'Bowtie (Gold)'
| 'Bowtie (Black)'
| 'Collar (Black)'
| 'Collar (Pink)'
| 'Dog Tags'
| 'VIP lanyard'
| 'FLUF Logo Chain'
| 'Bone Necklace'
| 'Glowstick Necklace'
| 'Gold Chain'
| 'Lei'
| 'Peace Necklace'
| 'Tie'
| 'Clock Necklace'
| 'Headphones'
| 'Greenstone'
| 'Gold Dollar Chain'
| 'POTA Lanyard'

export type Nose =

| 'Bull Ring'
| 'Steel Stud'
| 'Steel Ring'
| 'Bone'
| 'Gold Ring'
| 'Gold Stud'
| 'Clown Nose'
| 'Diamond Stud'
| 'Bloody'
| 'Glowing Red'
| 'Glowing White'
| 'Gold'
| 'Silver'

export type Sex =

| 'Male'
| 'Female'

export type Top =

| 'High Vis Vest'
| 'Boob Tube'
| 'Leather Vest'
| 'Flannel Jacket'
| 'Kimono'
| 'Digital Camo Singlet'
| 'Camo Jacket'
| 'FLUF Jacket'
| 'Pink Jacket'
| 'Sing My Carrot Singlet'
| 'Voxel Rabbit Singlet'
| 'Yellow Rabbit Singlet'
| 'Tie Dye Singlet'
| 'Puffer Vest'
| 'White Singlet'
| 'Black FLUF Singlet'
| 'Dress'
| 'Red Balloon Singlet'
| 'Puffer Jacket'
| 'Gold Jacket'
| 'Holographic Jacket'
