// For nftValuation

//Filters
export const TraitFilter = [
	{
		name: "Background",
		description: "background",
	},
	{
		name: "Dance",
		description: "dance",
	},
	{
		name: "Music",
		description: "music",
	},
	{
		name: "Expression",
		description: "expression",
	},
	{
		name: "Ears",
		description: "ears",
	},
	{
		name: "Nose",
		description: "nose",
	},
	{
		name: "Mouth",
		description: "mouth",
	},
	{
		name: "Head",
		description: "head",
	},
	{
		name: "Neck",
		description: "neck",
	},
	{
		name: "Top",
		description: "top",
	},
	{
		name: "Eyewear",
		description: "eyewear",
	},
	{
		name: "Eyes",
		description: "eyes",
	},
	{
		name: "Fur",
		description: "fur",
	},
	{
		name: "Sex",
		description: "sex",
	},
];

//First Filter
export const Status = [
	{
		name: "Listed",
		description: "listed",
	},
	{
		name: "Not Listed",
		description: "not_listed",
	},
];

export type Currencies = 

| 'eth'
| 'usd'
| 'sol'


//Second Filter
// export type Price = {
// 	minPrice: number;
// 	maxPrice: number;
// 	currency: Currencies;
// };

//Last Filter
export const Background = [
	{ name: "Mansion", description: "" },
	{ name: "Heaven", description: "" },
	{ name: "Lambo", description: "" },
	{ name: "Beach", description: "" },
	{ name: "Backalley", description: "" },
	{ name: "Tiki", description: "" },
	{ name: "Gallery", description: "" },
	{ name: "Dunes", description: "" },
	{ name: "Spaceship", description: "" },
	{ name: "Swamp", description: "" },
	{ name: "Garden", description: "" },
	{ name: "Markets", description: "" },
	{ name: "Pass", description: "" },
	{ name: "FTW (F*ck The War)", description: "" },
	{ name: "Mystic Valley", description: "" },
	{ name: "Thank You For Having Us", description: "" },
	{ name: "The Front", description: "" },
	{ name: "Dancing in the Shroomlight", description: "" },
	{ name: "FLUF Haus Miami 2021", description: "" },
	{ name: "Star Explorer", description: "" },
	{ name: "ASTO Discovery Portal", description: "" },
	{ name: "After Party", description: "" },
	{ name: "Fluf Haus LA 2022", description: "" },
	{ name: "The Wall", description: "" },
	{ name: "Pre-Game", description: "" },
	{ name: "Forest", description: "" },
	{ name: "Studio", description: "" },
	{ name: "Art Gallery", description: "" },
	{ name: "Desert", description: "" },
	{ name: "Space Hangar", description: "" },
	{ name: "Apocalypse", description: "" },
	{ name: "Igloo", description: "" },
	{ name: "Playa", description: "" },
	{ name: "Party House", description: "" },
	{ name: "Pj Runway", description: "" },
	{ name: "Zen Den", description: "" },
	{ name: "High School", description: "" },
	{ name: "Club", description: "" },
	{ name: "Temple", description: "" },
];
export const Dance = [
	{ name: "Groove", description: "" },
	{ name: "Bob", description: "" },
	{ name: "Side To Side", description: "" },
	{ name: "Subtle Nod", description: "" },
	{ name: "Round", description: "" },
	{ name: "Big Nod", description: "" },
	{ name: "Side Nod", description: "" },
	{ name: "Turn", description: "" },
];
export const Ears = [
	{ name: "Steel Rings", description: "" },
	{ name: "Steel Studs", description: "" },
	{ name: "Steel Rings & Studs", description: "" },
	{ name: "Gold Rings", description: "" },
	{ name: "FLUF Tag", description: "" },
	{ name: "Gold Bows", description: "" },
	{ name: "Gold Rings & Studs", description: "" },
	{ name: "Red Ribbon", description: "" },
	{ name: "Bandaged", description: "" },
	{ name: "Diamond Studs", description: "" },
	{ name: "Bit Ear", description: "" },
	{ name: "Diamond Cross Earring", description: "" },
	{ name: "Santa Hat", description: "" },
];
export const Expression = [
	{ name: "Mouth Open (Right)", description: "" },
	{ name: "Blank", description: "" },
	{ name: "Anger", description: "" },
	{ name: "Mouth Open (Middle)", description: "" },
	{ name: "Mouth Open (Right) + Wink", description: "" },
	{ name: "Mouth Open (Left)", description: "" },
	{ name: "Smile", description: "" },
	{ name: "Smile + Wink", description: "" },
	{ name: "Sad", description: "" },
	{ name: "Grin", description: "" },
	{ name: "Blank + Wink", description: "" },
	{ name: "Mouth Open (Middle) + Wink", description: "" },
	{ name: "Mouth Open (Left) + Wink", description: "" },
	{ name: "Wonder", description: "" },
	{ name: "Grin + Wink", description: "" },
];
export const Eyes = [
	{ name: "Green", description: "" },
	{ name: "Brown", description: "" },
	{ name: "Blue", description: "" },
	{ name: "Yellow", description: "" },
	{ name: "Green (Dilated)", description: "" },
	{ name: "Cat (Blue)", description: "" },
	{ name: "Cat (Brown)", description: "" },
	{ name: "Purple", description: "" },
	{ name: "Red", description: "" },
	{ name: "Fire", description: "" },
	{ name: "Heart (Blue)", description: "" },
	{ name: "Red (Dilated)", description: "" },
	{ name: "Thirties", description: "" },
	{ name: "Heart (Red)", description: "" },
	{ name: "Scribble", description: "" },
	{ name: "Dollars", description: "" },
	{ name: "Xs", description: "" },
	{ name: "Reptile (Yellow)", description: "" },
	{ name: "Reptile (White)", description: "" },
	{ name: "Reptile (Cream)", description: "" },
	{ name: "Glowing Red", description: "" },
	{ name: "Demon", description: "" },
	{ name: "Blast", description: "" },
	{ name: "Glowing White", description: "" },
	{ name: "Portal", description: "" },
	{ name: "Dead", description: "" },
	{ name: "Hypnotic", description: "" },
	{ name: "Mandala", description: "" },
	{ name: "Purple Rings", description: "" },
	{ name: "Inverted", description: "" },
	{ name: "Inverted (Purple)", description: "" },
	{ name: "Zombie", description: "" },
	{ name: "Zombie (Inverted)", description: "" },
	{ name: "Gold", description: "" },
	{ name: "Silver", description: "" },
];
export const Eyewear = [
	{ name: "Sunglasses", description: "" },
	{ name: "Shutter Glasses", description: "" },
	{ name: "Aviator", description: "" },
	{ name: "Star Glasses", description: "" },
	{ name: "Designer Glasses", description: "" },
	{ name: "Round Glasses", description: "" },
	{ name: "Bug Eye Glasses", description: "" },
	{ name: "Neon Glasses", description: "" },
	{ name: "Heart Glasses", description: "" },
	{ name: "Fake Eyelashes", description: "" },
	{ name: "Speed Glasses", description: "" },
	{ name: "Dive Goggles", description: "" },
	{ name: "Eye Patch", description: "" },
	{ name: "Safety Glasses", description: "" },
	{ name: "Cyberpunk Glasses", description: "" },
	{ name: "Deal With It Glasses", description: "" },
	{ name: "3D Glasses", description: "" },
	{ name: "Steampunk Goggles", description: "" },
];
export const Fur = [
	{ name: "Grey", description: "" },
	{ name: "Winter", description: "" },
	{ name: "Brown", description: "" },
	{ name: "Black & White", description: "" },
	{ name: "Sandy", description: "" },
	{ name: "Darkness", description: "" },
	{ name: "Peppermint", description: "" },
	{ name: "Orange", description: "" },
	{ name: "Red", description: "" },
	{ name: "Sky", description: "" },
	{ name: "Camo", description: "" },
	{ name: "Zebra", description: "" },
	{ name: "Tiger", description: "" },
	{ name: "Cow", description: "" },
	{ name: "Cheetah", description: "" },
	{ name: "Moody Blue", description: "" },
	{ name: "Marshmellow", description: "" },
	{ name: "Ice Cream", description: "" },
	{ name: "Raspberry Ripple", description: "" },
	{ name: "Smoothie", description: "" },
	{ name: "Honeycomb", description: "" },
	{ name: "Candy Floss", description: "" },
	{ name: "Parrot", description: "" },
	{ name: "Bully", description: "" },
	{ name: "Tie Dye", description: "" },
	{ name: "Highlighter", description: "" },
	{ name: "Hawk", description: "" },
	{ name: "Retro", description: "" },
	{ name: "Guernica", description: "" },
	{ name: "Blue Blood", description: "" },
	{ name: "Pheonix", description: "" },
	{ name: "Zombie (Black)", description: "" },
	{ name: "Zombie (Grey)", description: "" },
	{ name: "Zombie (Green)", description: "" },
	{ name: "Zombie (Red)", description: "" },
	{ name: "Barney", description: "" },
	{ name: "Grinch", description: "" },
	{ name: "Kandinsky", description: "" },
	{ name: "Hirst", description: "" },
	{ name: "Kanagawa", description: "" },
	{ name: "Blossom", description: "" },
	{ name: "Starry Night", description: "" },
	{ name: "Avatar", description: "" },
	{ name: "Holographic", description: "" },
	{ name: "Silver", description: "" },
	{ name: "Gold", description: "" },
];
export const Head = [
	{ name: "Beanie", description: "" },
	{ name: "Flower Crown", description: "" },
	{ name: "Bandana", description: "" },
	{ name: "Birthday Hat", description: "" },
	{ name: "Conical Hat", description: "" },
	{ name: "Cowboy Hat", description: "" },
	{ name: "Pirate Hat", description: "" },
	{ name: "Tuft (Base)", description: "" },
	{ name: "Mohawk (Base)", description: "" },
	{ name: "Afro (Base)", description: "" },
	{ name: "Army Helmet", description: "" },
	{ name: "FLUF Cap", description: "" },
	{ name: "Mullet (Base)", description: "" },
	{ name: "Sombrero", description: "" },
	{ name: "Propeller Hat", description: "" },
	{ name: "Tennis Hat", description: "" },
	{ name: "Sun Visor", description: "" },
	{ name: "Tuft (Black)", description: "" },
	{ name: "Tuft (Blonde)", description: "" },
	{ name: "Devil Horns", description: "" },
	{ name: "Mohawak (Red)", description: "" },
	{ name: "Mullet (Black)", description: "" },
	{ name: "Mohawak (Black)", description: "" },
	{ name: "Afro (Ginger)", description: "" },
	{ name: "Halo", description: "" },
	{ name: "Mullet (Orange)", description: "" },
	{ name: "Afro (Black)", description: "" },
	{ name: "Gold Cap", description: "" },
	{ name: "Beer Hat", description: "" },
	{ name: "Holographic Cap", description: "" },
	{ name: "Crown", description: "" },
];
export const Mouth = [
	{ name: "Lollipop", description: "" },
	{ name: "Joint", description: "" },
	{ name: "Cigarette", description: "" },
	{ name: "Carrot", description: "" },
	{ name: "Pipe", description: "" },
	{ name: "Party Horn", description: "" },
	{ name: "Whistle", description: "" },
	{ name: "Lip Piercings", description: "" },
	{ name: "Cigar", description: "" },
	{ name: "Pacifier", description: "" },
	{ name: "Lipstick", description: "" },
	{ name: "Medical Mask", description: "" },
	{ name: "Tongue Out", description: "" },
	{ name: "Mooncrust Pizza", description: "" },
	{ name: "Demon Mask", description: "" },
];
export const Music = [
	{ name: "Follow You", description: "" },
	{ name: "Run Rabbit", description: "" },
	{ name: "Coffee and Carrots", description: "" },
	{ name: "Ear Wobbler", description: "" },
	{ name: "Reggae Rabbits", description: "" },
	{ name: "Disco Rabbit", description: "" },
	{ name: "Electric Carrots", description: "" },
	{ name: "Desert Digging", description: "" },
	{ name: "Rabbiton", description: "" },
	{ name: "Space Fluffle", description: "" },
	{ name: "Floating or Flying", description: "" },
	{ name: "Hop On By", description: "" },
	{ name: "Back in the Burrow", description: "" },
	{ name: "Eating Carrots in the Dark", description: "" },
	{ name: "Dubhop", description: "" },
	{ name: "FLUF You Up", description: "" },
	{ name: "What the FLUF", description: "" },
	{ name: "I Like to Party", description: "" },
	{ name: "Beyond the Gates", description: "" },
	{ name: "Hop With Me", description: "" },
	{ name: "NFT (Instrumental)", description: "" },
	{ name: "I Love FLUF", description: "" },
	{ name: "Messiah", description: "" },
	{ name: "Let The Story Begin", description: "" },
	{ name: "FLUF Ocean", description: "" },
	{ name: "L.O.V.E.", description: "" },
	{ name: "Stardust", description: "" },
	{ name: "Lucky Foot", description: "" },
	{ name: "Higher", description: "" },
	{ name: "Latin Fiesta", description: "" },
	{ name: "All I Need", description: "" },
	{ name: "Shadows", description: "" },
	{ name: "Wouldn't It Be", description: "" },
	{ name: "Eating Carrots_in_the_Dark", description: "" },
	{ name: "How Could You", description: "" },
	{ name: "Let It Go", description: "" },
	{ name: "I Like_to_Party", description: "" },
	{ name: "Hop On_By", description: "" },
	{ name: "Beyond the_Gates", description: "" },
	{ name: "FLUF You_Up", description: "" },
	{ name: "What the_FLUF", description: "" },
	{ name: "Back in_the_Burrow", description: "" },
	{ name: "How You Feel", description: "" },
	{ name: "Floting or_Flying", description: "" },
	{ name: "Hop With_Me", description: "" },
	{ name: "Daft Bear", description: "" },
	{ name: "Tulum Bear", description: "" },
	{ name: "Altered Bear", description: "" },
	{ name: "Bear Marley", description: "" },
	{ name: "Bear Friends", description: "" },
	{ name: "Robobear", description: "" },
	{ name: "Show Bear Love", description: "" },
	{ name: "Tropical Bear", description: "" },
	{ name: "Bear Bass", description: "" },
	{ name: "Bear Bot", description: "" },
	{ name: "Bear Beach", description: "" },
	{ name: "Beartron", description: "" },
	{ name: "Ibiza Bear", description: "" },
	{ name: "Rufus Du Bear", description: "" },
	{ name: "Termabear", description: "" },
	{ name: "Rasta Bear", description: "" },
];
export const Neck = [
	{ name: "Bowtie (Red)", description: "" },
	{ name: "Bowtie (Gold)", description: "" },
	{ name: "Bowtie (Black)", description: "" },
	{ name: "Collar (Black)", description: "" },
	{ name: "Collar (Pink)", description: "" },
	{ name: "Dog Tags", description: "" },
	{ name: "VIP lanyard", description: "" },
	{ name: "FLUF Logo Chain", description: "" },
	{ name: "Bone Necklace", description: "" },
	{ name: "Glowstick Necklace", description: "" },
	{ name: "Gold Chain", description: "" },
	{ name: "Lei", description: "" },
	{ name: "Peace Necklace", description: "" },
	{ name: "Tie", description: "" },
	{ name: "Clock Necklace", description: "" },
	{ name: "Headphones", description: "" },
	{ name: "Greenstone", description: "" },
	{ name: "Gold Dollar Chain", description: "" },
	{ name: "POTA Lanyard", description: "" },
];
export const Nose = [
	{ name: "Bull Ring", description: "" },
	{ name: "Steel Stud", description: "" },
	{ name: "Steel Ring", description: "" },
	{ name: "Bone", description: "" },
	{ name: "Gold Ring", description: "" },
	{ name: "Gold Stud", description: "" },
	{ name: "Clown Nose", description: "" },
	{ name: "Diamond Stud", description: "" },
	{ name: "Bloody", description: "" },
	{ name: "Glowing Red", description: "" },
	{ name: "Glowing White", description: "" },
	{ name: "Gold", description: "" },
	{ name: "Silver", description: "" },
];
export const Sex = [
	{ name: "Male", description: "" },
	{ name: "Female", description: "" },
];
export const Top = [
	{ name: "High Vis Vest", description: "" },
	{ name: "Boob Tube", description: "" },
	{ name: "Leather Vest", description: "" },
	{ name: "Flannel Jacket", description: "" },
	{ name: "Kimono", description: "" },
	{ name: "Digital Camo Singlet", description: "" },
	{ name: "Camo Jacket", description: "" },
	{ name: "FLUF Jacket", description: "" },
	{ name: "Pink Jacket", description: "" },
	{ name: "Sing My Carrot Singlet", description: "" },
	{ name: "Voxel Rabbit Singlet", description: "" },
	{ name: "Yellow Rabbit Singlet", description: "" },
	{ name: "Tie Dye Singlet", description: "" },
	{ name: "Puffer Vest", description: "" },
	{ name: "White Singlet", description: "" },
	{ name: "Black FLUF Singlet", description: "" },
	{ name: "Dress", description: "" },
	{ name: "Red Balloon Singlet", description: "" },
	{ name: "Puffer Jacket", description: "" },
	{ name: "Gold Jacket", description: "" },
	{ name: "Holographic Jacket", description: "" },
];
